# Generated by Django 2.2.10 on 2020-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
