# Generated by Django 2.2.10 on 2020-08-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200717_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
