# Generated by Django 2.2.10 on 2020-08-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
