# Generated by Django 2.2.10 on 2020-09-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_nam',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
