# Generated by Django 2.2.10 on 2020-09-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200903_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_nam',
            new_name='first_name',
        ),
    ]
